### ISSUE TITLE
Adding build systems where the build file has a constant name

### ISSUE THREAD

**Issue by kirbyfan64** [ndmitchell/build-shootout#20]
Some build systems (most particularly Waf and fbuild) don't let you use a custom build script. In Waf's case, it must ALWAYS be named `wscript`; in fbuild's, `fbuildroot.py`. Could a way of getting around this be added to `Util.hs`?

**Comment by ndmitchell** [comment]
Sure. That bit runs in a temp directory, so if around line 130 you add the code:

    Waf -> do
        renameFile (name ++ "-wscript") "script"
        system_ "waf"

That should work just fine. If you have any difficulties just send me a patch you think should work for one of the tests, and I'll integrate it from there.

**Comment by kirbyfan64** [comment]
Woah, I just realized this was still open...whoops...
