### ISSUE TITLE
unchanged: Handle files which do not change for GNU Make

### ISSUE THREAD

**Issue by mkpankov** [ndmitchell/build-shootout#22]
I implemented [qake](https://github.com/mkpankov/qake) specifically with such case in mind: it shouldn't regenerate files which are built from sources, for which the timestamp changed, but the source itself did not. So changing `git` branch doesn't incur full rebuild, as well as re-linking of the program is done only if the object files did truly change (which is not the case if you, for example, simply add a comment and build w/o debugging info).

I didn't generate Makefiles, although I do shell out (at least for hashing of the sources). So I wonder if this implementation counts. The implementation uses "higher-order macros" of GNU Make to generate all the proper rules. And it uses GNU Make for the build description and dependency tracking itself. Basically, it's a glorified mega-macro rule which generates full set of GNU Make rules with the property of "unchanged files don't cause changes that would propagate; only immediate output is rebuilt".

I can expand on the details and give a full test case if you think this qualifies as shootout entry. The Qake is more than just that, but the essential mechanism making it work might be applied to pretty much any build system, I think.

**Comment by ndmitchell** [comment]
It sounds like no one would write the output qake generates directly in Makefile, and as such qake is better thought of as a separate tool which (as an implementation detail) generates Makefiles? If so, having entries in the shootout for qake seems quite reasonable. As soon as you are shelling out to hashing sources, it sounds like you've gone quite a bit beyond make.

**Comment by mkpankov** [comment]
You're probably right that no one would write this by hand. These multi level macros are quite unwieldy.
 
As for separate entry for qake - it's really prototype quality, so I doubt it would be useful. Don't want to mislead anyone into production use of the thing I implemented for fun and for the sake of it.
 
Thanks for offering, though! :)

**Comment by ndmitchell** [comment]
The shootout is really about the expressive power of the tool, not production quality, so I don't think it's misleading (and you can state "not production quality" at the top if you want). It's entirely up to you though.

**Comment by mkpankov** [comment]
Let me think about it for a while.

If I decide I'd like to add qake to shootout, should I just open a PR?

**Comment by ndmitchell** [comment]
Yep!

**Comment by mkpankov** [comment]
Fine, closing this then! :)
